### ISSUE TITLE
Blood Meter

### ISSUE THREAD

**Issue by misslame** [misslame/Vampizza#19]
Add a visual UI element for the blood meter, as well as the mechanics. 

** WARNING ** Communicate when you're working on UI to let those in the development team know not to work on UI at the same time as you. This is to avoid practically unfixable merge conflicts.

**Comment by jamsge** [comment]
as of https://github.com/misslame/Vampizza/commit/f7be40ad3f2f507d53c5b71c43c2c1ff8cd25cfc UI element is completed. Penalty for empty blood meter exists as a method in the Player class, but is not yet implemented. I will close in favor of https://github.com/misslame/Vampizza/issues/43, where blood bar mechanics can be finished.
