### ISSUE TITLE
Collect and Store Resources from Structures

### ISSUE THREAD

**Issue by misslame** [misslame/Vampizza#21]
Mechanics involved in collecting resources from structures.

**Comment by jamsge** [comment]
Related: https://github.com/misslame/Vampizza/issues/43

**Comment by jamsge** [comment]
As of https://github.com/misslame/Vampizza/commit/aa4b0969ffa71e6648fd6d0a5aa837477ef61662, harvesting wheat adds to the wheat resource in the inventory
