### ISSUE TITLE
Inventory and Shop UI/Population

### ISSUE THREAD

**Issue by misslame** [misslame/Vampizza#22]
Allow visual navigation of inventory and purchasing of structures.

**Comment by misslame** [comment]
How this is done is still up in the air. 

How is inventory/purchasing done? Should the inventory have purchase options for structures? separate shop? In the inventory what should be the UI elements, GameObjects with buttons/texts/images with information?

**Comment by jamsge** [comment]
Basic implementation finished and merged as of a while ago
