### ISSUE TITLE
**Bug** Pressing Space opens inventory

### ISSUE THREAD

**Issue by misslame** [misslame/Vampizza#25]
Pressing space opens up the inventory (doesn't close it) only when the inventory is closed. Can not find where this happens, may need another set of eyes.

**Comment by jamsge** [comment]
[Fixed here](https://github.com/misslame/Vampizza/pull/34)

Within the "Slider" UI component, under the Button settings there are settings to change Navigation. I don't exactly know the purpose of this but I think it has to do with accessibility (e.g. navigating menus with the arrow keys and space). Changed this setting to "None"
