### ISSUE TITLE
Task: Modify and Tweak Camera barriers. 

### ISSUE THREAD

**Issue by misslame** [misslame/Vampizza#36]
Barriers are fixed numbers and do not allow for the user to view the tips of the map when going up and down, but they can view the tips on the left and right. 

A decision needed: Should the user be able to reach the edge?

**Comment by jamsge** [comment]
I think it'd be pretty jarring to suddenly see the edge of the world when scrolling to the left or right. I think I will extend the ground tile map to encompass the entire range of the camera controller. Users should also not be able to build structures so close to or out of the edge of the visible world.

**Comment by jamsge** [comment]
Recently enlarged the ground tile map so the edges are not visible, as well as making it so players cannot build structures "out of bounds" in unreasonable areas.
